---
abstract: 'plugin system for the Taskwarrior task manager'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::Deep: '0'
  Test::MockObject: '0'
  Test::MockObject::Extends: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Taskwarrior-Kusarigama
provides:
  Taskwarrior::Kusarigama:
    file: lib/Taskwarrior/Kusarigama.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::App:
    file: lib/Taskwarrior/Kusarigama/App.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::App::Add:
    file: lib/Taskwarrior/Kusarigama/App/Add.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::App::Decimate:
    file: lib/Taskwarrior/Kusarigama/App/Decimate.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::App::Install:
    file: lib/Taskwarrior/Kusarigama/App/Install.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::App::Review:
    file: lib/Taskwarrior/Kusarigama/App/Review.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Core:
    file: lib/Taskwarrior/Kusarigama/Core.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Hook:
    file: lib/Taskwarrior/Kusarigama/Hook.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Hook::OnAdd:
    file: lib/Taskwarrior/Kusarigama/Hook/OnAdd.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Hook::OnCommand:
    file: lib/Taskwarrior/Kusarigama/Hook/OnCommand.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Hook::OnExit:
    file: lib/Taskwarrior/Kusarigama/Hook/OnExit.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Hook::OnLaunch:
    file: lib/Taskwarrior/Kusarigama/Hook/OnLaunch.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Hook::OnModify:
    file: lib/Taskwarrior/Kusarigama/Hook/OnModify.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Plugin:
    file: lib/Taskwarrior/Kusarigama/Plugin.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Plugin::Blocks:
    file: lib/Taskwarrior/Kusarigama/Plugin/Blocks.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Plugin::Command::AndAfter:
    file: lib/Taskwarrior/Kusarigama/Plugin/Command/AndAfter.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Plugin::Command::ButBefore:
    file: lib/Taskwarrior/Kusarigama/Plugin/Command/ButBefore.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Plugin::Command::Github:
    file: lib/Taskwarrior/Kusarigama/Plugin/Command/Github.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Plugin::Command::Mikado:
    file: lib/Taskwarrior/Kusarigama/Plugin/Command/Mikado.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Plugin::Command::Morning:
    file: lib/Taskwarrior/Kusarigama/Plugin/Command/Morning.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Plugin::Command::Open:
    file: lib/Taskwarrior/Kusarigama/Plugin/Command/Open.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Plugin::Command::Progress:
    file: lib/Taskwarrior/Kusarigama/Plugin/Command/Progress.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Plugin::Command::Wait:
    file: lib/Taskwarrior/Kusarigama/Plugin/Command/Wait.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Plugin::GitCommit:
    file: lib/Taskwarrior/Kusarigama/Plugin/GitCommit.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Plugin::Morning:
    file: lib/Taskwarrior/Kusarigama/Plugin/Morning.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Plugin::ProjectAlias:
    file: lib/Taskwarrior/Kusarigama/Plugin/ProjectAlias.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Plugin::ProjectDefaults:
    file: lib/Taskwarrior/Kusarigama/Plugin/ProjectDefaults.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Plugin::Renew:
    file: lib/Taskwarrior/Kusarigama/Plugin/Renew.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Plugin::SingleActive:
    file: lib/Taskwarrior/Kusarigama/Plugin/SingleActive.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Task:
    file: lib/Taskwarrior/Kusarigama/Task.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Wrapper:
    file: lib/Taskwarrior/Kusarigama/Wrapper.pm
    version: v0.12.0
  Taskwarrior::Kusarigama::Wrapper::Exception:
    file: lib/Taskwarrior/Kusarigama/Wrapper/Exception.pm
    version: v0.12.0
requires:
  Carp: '0'
  Clone: '0'
  DateTime::Functions: '0'
  File::HomeDir: '0'
  Hash::Diff: '0'
  Hash::Merge: '0'
  IO::Prompt::Simple: '0'
  IPC::Open3: '0'
  IPC::Run3: '0'
  JSON: '0'
  List::AllUtils: '0'
  List::MoreUtils: '0'
  List::Util: '0'
  List::UtilsBy: '0'
  Module::Runtime: '0'
  Moo: '0'
  Moo::Role: '0'
  MooseX::App: '0'
  MooseX::App::Command: '0'
  MooseX::MungeHas: '0'
  Net::GitHub: '0'
  Path::Tiny: '0'
  PerlX::Maybe: '0'
  Prompt::ReadKey: '0'
  Set::Object: '0'
  Symbol: '0'
  Template::Mustache: '0'
  Term::ANSIScreen: '0'
  Try::Tiny: '0'
  experimental: '0'
  namespace::clean: '0'
  overload: '0'
  perl: v5.20.0
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Taskwarrior-Kusarigama/issues
  homepage: https://github.com/yanick/Taskwarrior-Kusarigama
  repository: https://github.com/yanick/Taskwarrior-Kusarigama.git
version: 0.12.0
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributor_covenant:
  version: 0.01
x_contributors:
  - 'Alan Young <harleypig@harleypig.com>'
  - 'Chris Prather <chris@prather.org>'
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
  - 'Paul Fenwick <pjf@perltraining.com.au>'
  - 'pru.mike <pru.mike@gmail.com>'
  - 'Shawn Sorichetti <shawn@coloredblocks.com>'
  - 'Sweth Chandramouli <sweth.chandramouli@iinteractive.com>'
x_generated_by_perl: v5.20.2
x_serialization_backend: 'YAML::Tiny version 1.67'
